# Pair notebooks <-> scripts, mirroring folders
formats = "notebooks//ipynb,nbs//py:percent"
default_jupytext_formats = "ipynb,py:percent"

# Keep notebooks lightweight
cell_metadata_filter = "-all"
notebook_metadata_filter = "-all"


